# Generated by Django 3.2.9 on 2021-12-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishingDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
